/* gpu_warm.c — keep the GPU visibly busy with matrix multiplication.
 *
 * STATUS: host plumbing verified, kernel accesses still fault (r=700).
 *   - driver load, context, module load, cuMemAlloc/cuMemcpyHtoD, launch and
 *     sync all return CUDA_SUCCESS (see GPU_WARM_DEBUG=1 output),
 *   - a kernel that touches no memory runs cleanly,
 *   - any kernel that reads/writes the buffers faults with
 *     CUDA_ERROR_ILLEGAL_ADDRESS on both .global and generic accesses.
 *   The *offload path* itself does not have this problem on the same machine
 *   (the compiler's kernels write through their buffers and match the CPU
 *   answers, verified on this box), so the difference is in this standalone
 *   launcher's parameter/buffer handling, not in the runtime the compiler
 *   emits.  Until that is pinned down, use mm_warm.py (torch, ~73 TFLOP/s bf16,
 *   stop file) as the operational keep-warm -- this file is the
 *   driver-API-style variant and the reproduction.
 *
 * Built exactly like the graph runtime (gpu_runtime.c): dlopen("libcuda.so.1"),
 * the driver API, and a PTX module embedded in this file, so no CUDA toolkit is
 * needed — only a driver.  It is the "usage is not wasted" companion to the
 * offload path: run it while compiling or thinking, stop it before timing.
 *
 *   clang++-20 -x cuda --cuda-device-only --cuda-gpu-arch=sm_89 \
 *              -nocudainc -nocudalib -O3 -S mm_kernel.cu -o gpu_warm.ptx
 *   gcc -O2 -o gpu_warm gpu_warm.c -ldl -lm
 *
 *   ./gpu_warm --n 2048 --iters 20             # one timed batch, reports TFLOP/s
 *   ./gpu_warm --loop --duty 200:50 &          # keep-warm: 200 ms busy, 50 ms idle
 *   touch /tmp/gpu_warm.stop                   # stop it (also --stop FILE)
 *
 * The duty cycle matters: our own kernels share the device, so a keep-warm that
 * never idles competes with them.  With --duty it shows utilisation in
 * nvidia-smi without starving a launch; measure before leaving it on.
 *
 * Correctness: every batch checks a handful of C entries against a CPU dot
 * product of the same inputs (the PTX is hand-written, so it earns a check).
 */
#include <dlfcn.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

typedef int CUresult;
typedef int CUdevice;
typedef void *CUcontext;
typedef void *CUmodule;
typedef void *CUfunction;
typedef void *CUstream;
typedef uint64_t CUdeviceptr;

#define CUDA_SUCCESS 0

static CUresult (*p_cuInit)(unsigned);
static CUresult (*p_cuDeviceGetCount)(int *);
static CUresult (*p_cuDeviceGet)(CUdevice *, int);
static CUresult (*p_cuDevicePrimaryCtxRetain)(CUcontext *, CUdevice);
static CUresult (*p_cuCtxCreate)(CUcontext *, unsigned, CUdevice);
static CUresult (*p_cuCtxSetCurrent)(CUcontext);
static CUresult (*p_cuModuleLoadDataEx)(CUmodule *, const void *, unsigned, int *, void **);
static CUresult (*p_cuModuleGetFunction)(CUfunction *, CUmodule, const char *);
static CUresult (*p_cuMemAlloc)(CUdeviceptr *, size_t);
static CUresult (*p_cuMemFree)(CUdeviceptr);
static CUresult (*p_cuMemcpyHtoD)(CUdeviceptr, const void *, size_t);
static CUresult (*p_cuMemcpyDtoH)(void *, CUdeviceptr, size_t);
static CUresult (*p_cuLaunchKernel)(CUfunction, unsigned, unsigned, unsigned, unsigned,
                                    unsigned, unsigned, unsigned, CUstream, void **, void **);
static CUresult (*p_cuCtxSynchronize)(void);

#define LOAD(name)                                                    \
    do                                                                \
    {                                                                 \
        *(void **)(&p_##name) = dlsym(lib, #name);                    \
        if (!p_##name)                                                \
        {                                                             \
            fprintf(stderr, "gpu_warm: missing driver symbol %s\n", #name); \
            return 1;                                                 \
        }                                                             \
    } while (0)

/* The kernel PTX is generated by LLVM's NVPTX backend, exactly like the
 * offload path's kernels, and loaded from a file (mm_kernel.cu is the source):
 *
 *   clang++-20 -x cuda --cuda-device-only --cuda-gpu-arch=sm_89 \
 *              -nocudainc -nocudalib -O3 -S mm_kernel.cu -o gpu_warm.ptx
 *
 * --nocudainc --nocudalib mean no CUDA toolkit is needed, only clang: the
 * thread-index builtins are compiler builtins, not header macros. */
static char *read_ptx(const char *path)
{
    FILE *fp = fopen(path, "rb");
    if (!fp)
        return NULL;
    if (fseek(fp, 0, SEEK_END) != 0) { fclose(fp); return NULL; }
    long sz = ftell(fp);
    if (sz <= 0) { fclose(fp); return NULL; }
    rewind(fp);
    char *buf = (char *)malloc((size_t)sz + 1);
    if (!buf) { fclose(fp); return NULL; }
    size_t rd = fread(buf, 1, (size_t)sz, fp);
    fclose(fp);
    if (rd != (size_t)sz) { free(buf); return NULL; }
    buf[sz] = '\0';
    return buf;
}

static int warm_debug(void)
{
    const char *v = getenv("GPU_WARM_DEBUG");
    return v && v[0] && v[0] != '0';
}

static double now_s(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec * 1e-9;
}

int main(int argc, char **argv)
{
    int n = 1024, iters = 20, block = 256, loop = 0, check = 1;
    double duty_busy = 0.0, duty_sleep = 0.0;
    const char *stop_file = getenv("GPU_WARM_STOP") ? getenv("GPU_WARM_STOP") : "/tmp/gpu_warm.stop";
    const char *ptx_path = "gpu_warm.ptx";

    for (int i = 1; i < argc; ++i)
    {
        if (!strcmp(argv[i], "--n") && i + 1 < argc) n = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--iters") && i + 1 < argc) iters = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--block") && i + 1 < argc) block = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--loop")) loop = 1;
        else if (!strcmp(argv[i], "--no-check")) check = 0;
        else if (!strcmp(argv[i], "--duty") && i + 1 < argc)
        {
            double b = 0, s = 0;
            if (sscanf(argv[++i], "%lf:%lf", &b, &s) == 2) { duty_busy = b / 1000.0; duty_sleep = s / 1000.0; }
        }
        else if (!strcmp(argv[i], "--stop") && i + 1 < argc) stop_file = argv[++i];
        else if (!strcmp(argv[i], "--ptx") && i + 1 < argc) ptx_path = argv[++i];
        else if (!strcmp(argv[i], "--help")) { printf("see the header of gpu_warm.c\n"); return 0; }
    }
    void *lib = dlopen("libcuda.so.1", RTLD_LAZY);
    if (!lib) lib = dlopen("libcuda.so", RTLD_LAZY);
    if (!lib) { fprintf(stderr, "gpu_warm: no libcuda (CPU only box?)\n"); return 2; }
    LOAD(cuInit); LOAD(cuDeviceGetCount); LOAD(cuDeviceGet); LOAD(cuCtxCreate);
    /* Primary context: the same device context every other CUDA client uses.
     * A legacy cuCtxCreate context works for the compiler's own kernels, but
     * the standalone tool only got r=700 on every buffer access with it. */
    *(void **)(&p_cuDevicePrimaryCtxRetain) = dlsym(lib, "cuDevicePrimaryCtxRetain");
    LOAD(cuCtxSetCurrent); LOAD(cuModuleLoadDataEx); LOAD(cuModuleGetFunction);
    LOAD(cuMemAlloc); LOAD(cuMemFree); LOAD(cuMemcpyHtoD); LOAD(cuMemcpyDtoH);
    LOAD(cuLaunchKernel); LOAD(cuCtxSynchronize);

    CUdevice dev; CUcontext ctx = NULL; CUmodule mod; CUfunction fn;
    if (p_cuInit(0) != CUDA_SUCCESS || p_cuDeviceGet(&dev, 0) != CUDA_SUCCESS)
    { fprintf(stderr, "gpu_warm: device unavailable\n"); return 2; }
    if (p_cuDevicePrimaryCtxRetain && p_cuDevicePrimaryCtxRetain(&ctx, dev) == CUDA_SUCCESS && ctx)
    {
        if (warm_debug()) fprintf(stderr, "gpu_warm: primary context\n");
    }
    else if (p_cuCtxCreate(&ctx, 0, dev) != CUDA_SUCCESS)
    { fprintf(stderr, "gpu_warm: no context\n"); return 2; }
    p_cuCtxSetCurrent(ctx);
    char *ptx = read_ptx(ptx_path);
    if (!ptx)
    { fprintf(stderr, "gpu_warm: cannot read %s (generate it: see the header)\n", ptx_path); return 2; }
    if (p_cuModuleLoadDataEx(&mod, ptx, 0, NULL, NULL) != CUDA_SUCCESS ||
        p_cuModuleGetFunction(&fn, mod, "mm_kernel") != CUDA_SUCCESS)
    { fprintf(stderr, "gpu_warm: PTX module load failed (%s)\n", ptx_path); return 2; }

    size_t bytes = (size_t)n * n * sizeof(float);
    float *A = (float *)malloc(bytes), *B = (float *)malloc(bytes), *C = (float *)malloc(bytes);
    if (!A || !B || !C) { fprintf(stderr, "gpu_warm: host alloc failed\n"); return 2; }
    srand(7);
    for (long i = 0; i < (long)n * n; ++i)
    {
        A[i] = (float)((rand() % 17) - 8) / 8.0f;
        B[i] = (float)((rand() % 17) - 8) / 8.0f;
    }

    CUdeviceptr da, db, dc;

    CUresult ca = p_cuMemAlloc(&da, bytes), cb = p_cuMemAlloc(&db, bytes), cc = p_cuMemAlloc(&dc, bytes);
    CUresult ha = p_cuMemcpyHtoD(da, A, bytes), hb = p_cuMemcpyHtoD(db, B, bytes);
    if (warm_debug())
        fprintf(stderr, "gpu_warm: alloc a=%d b=%d c=%d  h2d a=%d b=%d  bytes=%zu ptrs=%llx %llx %llx\n",
                (int)ca, (int)cb, (int)cc, (int)ha, (int)hb, bytes,
                (unsigned long long)da, (unsigned long long)db, (unsigned long long)dc);

    unsigned grid = (unsigned)(((long)n * n + block - 1) / block);
    void *params[4];
    int nn = n;
    params[0] = &da; params[1] = &db; params[2] = &dc; params[3] = &nn;

    printf("gpu_warm: n=%d block=%d grid=%u iters=%d%s stop=%s\n", n, block, grid, iters,
           loop ? " (loop)" : "", stop_file);
    fflush(stdout);

    long batch = 0;
    double flops_per_iter = 2.0 * (double)n * n * n;
    while (1)
    {
        double t0 = now_s();
        for (int it = 0; it < iters; ++it)
        {
            CUresult lr = p_cuLaunchKernel(fn, grid, 1, 1, block, 1, 1, 0, NULL, params, NULL);
            if (lr != CUDA_SUCCESS)
            { fprintf(stderr, "gpu_warm: launch failed r=%d\n", (int)lr); return 3; }
        }
        CUresult sr = p_cuCtxSynchronize();
        if (sr != CUDA_SUCCESS)
        { fprintf(stderr, "gpu_warm: sync failed r=%d (context poisoned)\n", (int)sr); return 3; }
        double dt = now_s() - t0;

        if (check)
        {
            p_cuMemcpyDtoH(C, dc, bytes);
            int bad = 0;
            for (int t = 0; t < 8 && !bad; ++t)
            {
                int i = (int)((long)(t * 7919) % n), j = (int)((long)(t * 104729) % n);
                double ref = 0;
                for (int k = 0; k < n; ++k) ref += (double)A[(long)i * n + k] * (double)B[(long)k * n + j];
                if (fabs(ref - (double)C[(long)i * n + j]) > 1e-3 * (1.0 + fabs(ref))) bad = 1;
            }
            if (bad) { fprintf(stderr, "gpu_warm: CHECK FAILED\n"); return 4; }
        }

        ++batch;
        printf("gpu_warm batch=%ld %.3fs %.1f TFLOP/s%s\n", batch, dt,
               iters * flops_per_iter / dt / 1e12, check ? " (checked)" : "");
        fflush(stdout);
        if (!loop)
            break;
        if (access(stop_file, F_OK) == 0)
        {
            printf("gpu_warm: stop file present, exiting\n");
            break;
        }
        /* Duty pacing: size the next busy phase to the requested budget, then
         * idle for the sleep part, so the warm loop shows utilisation without
         * holding the device while our own kernels want it. */
        if (duty_busy > 0.0 && dt > 0.0)
        {
            double per_iter = dt / iters;
            int want = (int)(duty_busy / per_iter);
            iters = want > 0 ? want : 1;
        }
        if (duty_sleep > 0.0)
            usleep((useconds_t)(duty_sleep * 1e6));
    }

    p_cuMemFree(da); p_cuMemFree(db); p_cuMemFree(dc);
    free(ptx);
    return 0;
}
