site_name: GraphEasy
site_description: "An Efficient, Easy-to-Use DSL for Solving Graph Problems"
site_url: https://nash-raf.github.io/Graph-language-/
theme:
  name: material
  palette:
    primary: indigo

nav:
  - Home: index.md
  - Getting Started: tutorial.md
  - Language Manual: language.md
  - Grammar Reference: grammar.md
  - Algorithms: algorithms.md
  - Bron-Kerbosch: bron-kerbosch.md
  - Results: results.md

markdown_extensions:
  - tables
  - fenced_code
